/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-error": "#690005",
              "surface-container-high": "#292932",
              "on-primary-fixed-variant": "#2f2ebe",
              "tertiary-fixed-dim": "#ffb783",
              "on-secondary-fixed": "#002113",
              "inverse-surface": "#e4e1ed",
              "inverse-on-surface": "#303038",
              "coral-warning": "#fb7185",
              "surface-container": "#1f1f27",
              "inverse-primary": "#494bd6",
              "on-tertiary": "#4f2500",
              "on-error-container": "#ffdad6",
              "secondary-fixed-dim": "#4edea3",
              "outline": "#908fa0",
              "on-surface-variant": "#c7c4d7",
              "error": "#ffb4ab",
              "on-secondary-container": "#00311f",
              "tertiary-container": "#d97721",
              "surface-dim": "#13131b",
              "primary": "#c0c1ff",
              "surface-variant": "#34343d",
              "surface-container-low": "#1b1b23",
              "error-container": "#93000a",
              "surface-bright": "#393841",
              "on-tertiary-container": "#452000",
              "secondary-container": "#00a572",
              "on-tertiary-fixed-variant": "#703700",
              "indigo-primary": "#6366f1",
              "primary-fixed-dim": "#c0c1ff",
              "on-primary-container": "#0d0096",
              "on-tertiary-fixed": "#301400",
              "tertiary": "#ffb783",
              "on-primary-fixed": "#07006c",
              "background": "#13131b",
              "primary-fixed": "#e1e0ff",
              "secondary-fixed": "#6ffbbe",
              "primary-container": "#8083ff",
              "emerald-positive": "#10b981",
              "on-surface": "#e4e1ed",
              "on-background": "#e4e1ed",
              "surface-tint": "#c0c1ff",
              "on-secondary-fixed-variant": "#005236",
              "outline-variant": "#464554",
              "on-primary": "#1000a9",
              "on-secondary": "#003824",
              "secondary": "#4edea3",
              "violet-action": "#8b5cf6",
              "rose-alert": "#f43f5e",
              "amber-soft": "#f59e0b",
              "surface": "#13131b",
              "surface-container-lowest": "#0d0d15",
              "surface-container-highest": "#34343d",
              "surface-glass": "rgba(30, 41, 59, 0.7)",
              "tertiary-fixed": "#ffdcc5",
              "background-deep": "#0f172a"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-padding": "2rem",
              "card-padding": "1.25rem",
              "section-gap": "1.5rem",
              "grid-gutter": "1rem"
      },
      "fontFamily": {
              "display-metric": ["Manrope"],
              "delta-pill": ["Inter"],
              "label-caps": ["Inter"],
              "headline-md": ["Manrope"],
              "headline-lg": ["Manrope"],
              "body-sm": ["Inter"],
              "body-base": ["Inter"]
      },
      "fontSize": {
              "display-metric": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "delta-pill": ["12px", { "lineHeight": "12px", "fontWeight": "700" }],
              "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
              "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
