"""
main.py — FastAPI service wrapper for GovWorkflowEnv.

Session model
─────────────
Every POST /reset creates a new session identified by a UUID.
All subsequent calls (/step, /state, /grade) carry that session_id in the
request body. Sessions are kept in a thread-safe in-memory OrderedDict.
When the store reaches max_sessions capacity the oldest session is evicted
automatically (oldest-first FIFO eviction).

IMPORTANT: the in-memory store is NOT shared across multiple OS processes.
Run with workers=1 (the default from ServerSettings) to keep this correct.

Endpoint map
────────────
GET    /health                → server & session health
POST   /reset                 → create session, returns session_id + obs
POST   /step                  → advance one simulation tick
POST   /state                 → full episode state (action_history optional)
POST   /grade                 → task-specific deterministic grader
GET    /sessions              → list active session IDs
DELETE /sessions/{id}         → remove a session
GET    /docs                  → Swagger UI (auto-generated by FastAPI)
GET    /redoc                 → ReDoc UI (auto-generated by FastAPI)
"""

from __future__ import annotations

from collections import OrderedDict
from threading import Lock
from typing import Any
from uuid import uuid4

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from app.config import env_settings, server_settings
from app.env import GovWorkflowEnv
from app.graders import grade_episode
from app.models import ActionModel, EpisodeStateModel, ObservationModel, StepInfoModel
from app.tasks import list_tasks


# ── Session store ─────────────────────────────────────────────────────────────

class _SessionStore:
    """
    Thread-safe in-memory session registry.

    Design decisions:
    - Uses threading.Lock — safe for Uvicorn's single-worker async+thread model.
    - Uses OrderedDict so eviction is always oldest-first in O(1) via popitem.
    - Never imports from FastAPI. HTTP concerns (404 conversion) stay in
      endpoints. KeyError propagates upward and is converted to 404 there.
    """

    def __init__(self, max_sessions: int) -> None:
        self._store: OrderedDict[str, GovWorkflowEnv] = OrderedDict()
        self._lock = Lock()
        self._max = max_sessions

    def create(
        self,
        task_id: str,
        seed: int | None,
        options: dict[str, Any] | None,
    ) -> tuple[str, ObservationModel, dict[str, Any]]:
        env = GovWorkflowEnv(task_id=task_id)
        obs, info = env.reset(seed=seed, options=options)
        session_id = str(uuid4())
        with self._lock:
            if len(self._store) >= self._max:
                self._store.popitem(last=False)  # evict oldest
            self._store[session_id] = env
        return session_id, obs, info

    def get(self, session_id: str) -> GovWorkflowEnv:
        with self._lock:
            env = self._store.get(session_id)
        if env is None:
            raise KeyError(session_id)
        return env

    def delete(self, session_id: str) -> bool:
        with self._lock:
            return self._store.pop(session_id, None) is not None

    def active_count(self) -> int:
        with self._lock:
            return len(self._store)

    def list_ids(self) -> list[str]:
        with self._lock:
            return list(self._store.keys())


_sessions = _SessionStore(max_sessions=env_settings.max_sessions)


# ── Helper ────────────────────────────────────────────────────────────────────

def _get_or_404(session_id: str) -> GovWorkflowEnv:
    """Fetches a session env by ID or raises HTTP 404."""
    try:
        return _sessions.get(session_id)
    except KeyError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"Session '{session_id}' not found. "
                "Call POST /reset to create a new session."
            ),
        )


# ── API request / response schemas ────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    version: str
    active_sessions: int
    available_tasks: list[str]


class ResetRequest(BaseModel):
    task_id: str = Field(
        default=env_settings.default_task_id,
        description="Task to run. One of the three benchmark task IDs.",
    )
    seed: int | None = Field(
        default=None,
        description=(
            "RNG seed. Omit to use the task's built-in deterministic seed. "
            "Pass an explicit integer to replay the same episode."
        ),
    )
    options: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Optional overrides forwarded verbatim to env.reset(options=...). "
            "Supported key: 'task_id' to switch tasks inside an existing session."
        ),
    )


class ResetResponse(BaseModel):
    session_id: str
    observation: ObservationModel
    info: dict[str, Any]


class StepRequest(BaseModel):
    session_id: str = Field(description="Session ID returned by POST /reset.")
    action: ActionModel


class StepResponse(BaseModel):
    session_id: str
    observation: ObservationModel
    reward: float
    terminated: bool
    truncated: bool
    info: StepInfoModel


class StateRequest(BaseModel):
    session_id: str = Field(description="Session ID returned by POST /reset.")
    include_action_history: bool = Field(
        default=False,
        description=(
            "When False (default) the action_history list is stripped to keep "
            "payloads small. Set True to receive the full step-by-step action log."
        ),
    )


class StateResponse(BaseModel):
    session_id: str
    state: EpisodeStateModel


class GradeRequest(BaseModel):
    session_id: str = Field(description="Session ID returned by POST /reset.")


class GradeResponse(BaseModel):
    session_id: str
    score: float = Field(ge=0.0, le=1.0, description="Episode score in [0.0, 1.0].")
    grader_name: str
    metrics: dict[str, float]


class SessionListResponse(BaseModel):
    active_sessions: int
    session_ids: list[str]


class DeleteSessionResponse(BaseModel):
    deleted: str


# ── Application ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="Gov Workflow OpenEnv",
    summary="Government-service workflow control — OpenEnv-compatible HTTP API",
    description=(
        "A real-world OpenEnv-style environment where an AI agent reduces "
        "avoidable administrative delay in government-service workflows through "
        "queue prioritisation, missing-document handling, officer allocation, "
        "escalation control, SLA routing, and fairness management.\n\n"
        "**Quick start**\n"
        "1. `POST /reset` → get `session_id`\n"
        "2. `POST /step` with `session_id` + `action` repeatedly\n"
        "3. `POST /grade` to get the deterministic episode score\n"
        "4. `DELETE /sessions/{session_id}` to clean up\n"
    ),
    version="0.3.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=server_settings.cors_origins,  # ["*"] — required for HF Spaces
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["meta"],
    summary="Server and session health",
)
def health() -> HealthResponse:
    """Returns server status, version, active session count, and task list."""
    return HealthResponse(
        status="ok",
        version="0.3.0",
        active_sessions=_sessions.active_count(),
        available_tasks=list_tasks(),
    )


@app.post(
    "/reset",
    response_model=ResetResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["env"],
    summary="Create a new session and return the initial observation",
)
def reset(body: ResetRequest) -> ResetResponse:
    """
    Creates a fresh GovWorkflowEnv episode, registers it in the session store,
    and returns a unique session_id with the initial observation.

    Use seed for reproducible episodes. Use options to override task_id
    when switching tasks within a long-running client.
    """
    session_id, obs, info = _sessions.create(
        task_id=body.task_id,
        seed=body.seed,
        options=body.options,
    )
    return ResetResponse(session_id=session_id, observation=obs, info=info)


@app.post(
    "/step",
    response_model=StepResponse,
    tags=["env"],
    summary="Advance the simulation by one tick",
)
def step(body: StepRequest) -> StepResponse:
    """
    Applies one ActionModel to the session's environment and returns
    the next observation, reward, termination flags, and step info.

    Returns 409 Conflict if the episode has already ended — call
    POST /reset to start a fresh episode.
    """
    env = _get_or_404(body.session_id)
    if env.terminated or env.truncated:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                "Episode has already ended (terminated or truncated). "
                "Call POST /reset to start a new episode."
            ),
        )
    obs, reward, terminated, truncated, info = env.step(body.action)
    return StepResponse(
        session_id=body.session_id,
        observation=obs,
        reward=reward,
        terminated=terminated,
        truncated=truncated,
        info=info,
    )


@app.post(
    "/state",
    response_model=StateResponse,
    tags=["env"],
    summary="Return the full internal episode state",
)
def state(body: StateRequest) -> StateResponse:
    """
    Returns the complete EpisodeStateModel for the given session.

    Set include_action_history: true to receive the full step-by-step log.
    Default is false to keep response payloads small during agent loops.
    """
    env = _get_or_404(body.session_id)
    episode_state = env.state()
    if not body.include_action_history:
        episode_state = episode_state.model_copy(update={"action_history": []})
    return StateResponse(session_id=body.session_id, state=episode_state)


@app.post(
    "/grade",
    response_model=GradeResponse,
    tags=["env"],
    summary="Run the deterministic task grader for the current episode",
)
def grade(body: GradeRequest) -> GradeResponse:
    """
    Runs the task-specific deterministic grader against the current episode
    state and returns a score in [0.0, 1.0] plus per-metric breakdowns.

    Can be called at any point — not only at termination.
    """
    env = _get_or_404(body.session_id)
    result = grade_episode(env.state())
    return GradeResponse(
        session_id=body.session_id,
        score=result.score,
        grader_name=result.grader_name,
        metrics=result.metrics,
    )


@app.get(
    "/sessions",
    response_model=SessionListResponse,
    tags=["meta"],
    summary="List all active session IDs",
)
def list_sessions() -> SessionListResponse:
    """Returns the count and IDs of all currently active sessions."""
    return SessionListResponse(
        active_sessions=_sessions.active_count(),
        session_ids=_sessions.list_ids(),
    )


@app.delete(
    "/sessions/{session_id}",
    response_model=DeleteSessionResponse,
    tags=["meta"],
    summary="Delete a session and free its memory",
)
def delete_session(session_id: str) -> DeleteSessionResponse:
    """
    Removes the session from the store and releases its GovWorkflowEnv instance.
    Returns 404 if the session does not exist.
    """
    deleted = _sessions.delete(session_id)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session '{session_id}' not found.",
        )
    return DeleteSessionResponse(deleted=session_id)


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app.main:app",
        host=server_settings.host,
        port=server_settings.port,
        log_level=server_settings.log_level,
        workers=server_settings.workers,  # always 1 for in-memory sessions
        reload=False,
    )